-- 0013_dashboard_briefing.sql
--
-- Cache table for the dashboard's AI briefing. The briefing is a 2-3
-- sentence narrative summary of the last 24h, generated by Claude
-- against numeric aggregates (no prompts, no completions). Cached for
-- ~1 hour per user to avoid hitting the Anthropic API on every page
-- render.
--
-- `source` distinguishes AI-generated text from the deterministic
-- templated fallback that runs when the API is unavailable. The
-- dashboard renders both with the same UI, but reading from this
-- column lets us audit the AI hit rate.

CREATE TABLE IF NOT EXISTS dashboard_briefing (
  id            UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id       UUID         NOT NULL,
  text          TEXT         NOT NULL,
  source        TEXT         NOT NULL CHECK (source IN ('ai', 'fallback')),
  generated_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS dashboard_briefing_user_recent_idx
  ON dashboard_briefing (user_id, generated_at DESC);
