/**
 * /billing/export — engagement billing export page.
 *
 * Server component that loads org + project list, enforces the Pro+
 * plan-gate, then renders the ExportForm client component.
 *
 * The actual CSV is generated by GET /api/billing/export (see
 * app/api/billing/export/route.ts) — this page is only the form UI.
 */

import type { ReactElement } from "react";
import { redirect } from "next/navigation";
import { currentUser } from "@/lib/current-user";
import { primaryOrgForUser } from "@/lib/org-db";
import { limitsFor } from "@/lib/plan-gate";
import { listProjects } from "@/lib/project-db";

import { Header } from "@/components/Header";
import { DashboardShell } from "@/components/ui/DashboardShell";
import { Card, CardHeader } from "@/components/ui/Card";
import { Banner } from "@/components/ui/Banner";
import { palette, space } from "@/lib/theme";

import { ExportForm, type ProjectOption } from "./ExportForm";

export const dynamic = "force-dynamic";

export default async function BillingExportPage(): Promise<ReactElement> {
  const me = await currentUser();
  if (!me) redirect("/login");

  const org = await primaryOrgForUser(me.id);
  if (!org) {
    return (
      <DashboardShell>
        <Header me={me} active="billing" />
        <Card>
          <CardHeader title="Billing Export" />
          <p style={{ color: palette.textDim }}>
            No organization yet. Create a project first.
          </p>
        </Card>
      </DashboardShell>
    );
  }

  const limits = limitsFor(org);

  // Pro+ gate — free users see an upgrade prompt instead of the form.
  if (!limits.ai_features) {
    return (
      <DashboardShell>
        <Header me={me} active="billing" />
        <Card>
          <CardHeader title="Billing Export" />
          <Banner variant="warning">
            Billing export requires a Pro or Team plan.{" "}
            <a href="/billing" style={{ color: palette.cyan }}>Upgrade at /billing</a>.
          </Banner>
        </Card>
      </DashboardShell>
    );
  }

  const projectRows = await listProjects(me.id);
  const projects: ProjectOption[] = projectRows.map((p) => ({
    id: p.id,
    name: p.name,
  }));

  return (
    <DashboardShell>
      <Header me={me} active="billing" />
      <div style={{ display: "flex", flexDirection: "column", gap: space.x4 }}>
        <Card>
          <CardHeader title="Engagement Billing Export" />
          <p style={{ color: palette.textDim, fontSize: 13, marginBottom: space.x4 }}>
            Download a CSV of AI usage aggregated by day, repo, and model for
            a selected project. Use this to invoice clients for AI engineering work.
          </p>

          <ExportForm projects={projects} />
        </Card>

        <Card>
          <CardHeader title="CSV columns" />
          <div style={{ display: "grid", gridTemplateColumns: "auto 1fr", gap: `${space.x1}px ${space.x4}px`, fontSize: 12 }}>
            <ColName>date</ColName>
            <ColDesc>Calendar day (YYYY-MM-DD, UTC)</ColDesc>

            <ColName>repo</ColName>
            <ColDesc>Repository full name</ColDesc>

            <ColName>model</ColName>
            <ColDesc>AI model used (e.g. claude-sonnet-4-5)</ColDesc>

            <ColName>hours_worked</ColName>
            <ColDesc>
              Wall-clock hours between first and last event on that day + repo,
              capped at 8 h. A cap flag is set internally when the raw span
              exceeds 8 h (e.g. a session left running overnight).
            </ColDesc>

            <ColName>tokens_input</ColName>
            <ColDesc>Total input tokens</ColDesc>

            <ColName>tokens_output</ColName>
            <ColDesc>Total output tokens</ColDesc>

            <ColName>cost_usd</ColName>
            <ColDesc>Rate-card cost in USD (6 decimal places)</ColDesc>

            <ColName>event_count</ColName>
            <ColDesc>Number of activity events in the bucket</ColDesc>
          </div>
          <p style={{ fontSize: 11, color: palette.textMute, marginTop: space.x3 }}>
            Privacy: exports contain only metadata (timestamps, token counts,
            cost). No prompts, completions, or raw OTel spans are included.
          </p>
        </Card>
      </div>
    </DashboardShell>
  );
}

function ColName({ children }: { children: React.ReactNode }): ReactElement {
  return (
    <code style={{ color: palette.cyan, fontSize: 11, fontFamily: "var(--font-mono), monospace", alignSelf: "start", paddingTop: 1 }}>
      {children}
    </code>
  );
}

function ColDesc({ children }: { children: React.ReactNode }): ReactElement {
  return <span style={{ color: palette.textDim }}>{children}</span>;
}
